api-version: 1.15
load: POSTWORLD
depend: [ProtocolLib, NBTAPI, PacketWrapper]
name: rmAPIs
main: rmMinusR.mc.plugins.apis.RmApisPlugin
version: 0.5b build 11
commands:
 rmapis-debug:
  usage: /<command> tag <set:list:clear> [key] [value]
  description: Debugging
  permission: rmapis.debug
permissions:
 rmapis.debug:
  description: Debugging RMAPIS
  default: op
